apiVersion: v1
kind: Service
metadata:
  name: bookmyshow-service
  labels:
    app: bookmyshow
spec:
  selector:
    app: bookmyshow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer